import assert from "node:assert/strict";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import test from "node:test";

import { runAuditFix } from "../plugins/council/scripts/lib/audit-fix.mjs";
import { makeProgressReporter } from "../plugins/council/scripts/lib/progress.mjs";

// Phase 2 / Task 3 — runAuditFix must actually FEED the progress reporter (anti-facade: a wired path
// with no test proving the call is not wired). Every case here drives the REAL runAuditFix with an
// injected git + adapters (no network, no real repo) and a REAL makeProgressReporter, then asserts the
// live counters/gate the dashboard reads move on a fixed vs reverted vs proposed outcome.

const tmp = () => fs.mkdtempSync(path.join(os.tmpdir(), "council-fix-progress-"));

function fakeGit({ clean = true, repo = true } = {}) {
  const calls = [];
  let head = "base0000ffffffff";
  let changed = [];
  return {
    calls,
    setChanged(c) {
      changed = c;
    },
    isRepo: () => repo,
    isClean: () => clean,
    head: () => head,
    currentBranch: () => "master",
    createAndCheckout: (b, ref) => calls.push(["createAndCheckout", b, ref]),
    checkout: (r) => (calls.push(["checkout", r]), true),
    changedFiles: () => changed,
    resetHard: (ref) => {
      calls.push(["resetHard", ref]);
      changed = [];
    },
    commitFile: (file, msg) => {
      calls.push(["commitFile", file, msg]);
      head = `commit${calls.length}`;
      changed = [];
      return head;
    }
  };
}

const baseDeps = (git, over = {}) => ({
  git,
  fileExists: () => true,
  readFile: () => "export const x = 1;\n",
  testCmd: { cmd: "true", args: [] },
  runTests: async () => ({ ok: true }),
  resolveLedger: () => true,
  ...over
});

const loc = (o) => ({ severity: "P1", scope: "localized", ...o });
const sensitiveGit = (o) => Object.assign(fakeGit(o), { diffText: () => "@@ -1 +1 @@\n-old\n+new\n" });
const race = (o) => loc({ file: "a.mjs", title: "fix the race", category: "concurrency", ...o });

function reporterWithSink() {
  const writes = [];
  const reporter = makeProgressReporter({
    kind: "audit-fix-loop",
    title: "audit fix",
    stateDir: "C:/state",
    now: () => "2026-07-13T00:00:00.000Z",
    writeFile: (file, data) => writes.push({ file, data })
  });
  return { reporter, writes };
}

test("runAuditFix reporter: a committed fix bumps fixed + committed and announces the fix phase", async () => {
  const git = fakeGit();
  const { reporter, writes } = reporterWithSink();
  const out = await runAuditFix(tmp(), [loc({ file: "a.mjs", title: "fix me" })], {}, { reporter }, baseDeps(git, { applyFix: async () => git.setChanged(["a.mjs"]) }));
  assert.equal(out.fixed.length, 1, "the fix still commits (reporter is additive)");

  const snap = reporter.snapshot();
  assert.equal(snap.phase, "fix", "the fix phase was announced");
  assert.equal(snap.counters.fixed, 1, "a kept fix bumps the fixed counter");
  assert.equal(snap.counters.committed, 1, "and the committed counter");
  assert.ok(!snap.counters.reverted, "nothing was reverted");
  assert.ok(writes.length > 0, "progress.json was persisted through the injected writeFile");
});

test("runAuditFix reporter: an applied fix reverted by a failing test bumps reverted, not fixed", async () => {
  const git = fakeGit();
  const { reporter } = reporterWithSink();
  const out = await runAuditFix(tmp(), [loc({ file: "a.mjs", title: "fix" })], {}, { reporter }, baseDeps(git, {
    applyFix: async () => git.setChanged(["a.mjs"]),
    runTests: async () => ({ ok: false, output: "1 failing" })
  }));
  assert.equal(out.fixed.length, 0);
  const snap = reporter.snapshot();
  assert.equal(snap.counters.reverted, 1, "the post-apply gate revert bumps reverted");
  assert.ok(!snap.counters.fixed, "and never the fixed counter");
});

test("runAuditFix reporter: a propose-only finding (content-protected) bumps proposed, never applied", async () => {
  const git = fakeGit();
  const { reporter } = reporterWithSink();
  let applied = 0;
  const out = await runAuditFix(tmp(), [loc({ file: "a.mjs", title: "touch generated" })], {}, { reporter }, baseDeps(git, {
    readFile: () => "// @generated by tool\nexport const x = 1;\n",
    applyFix: async () => { applied += 1; git.setChanged(["a.mjs"]); }
  }));
  assert.equal(applied, 0, "content-protected source is never handed to the writer");
  assert.equal(out.fixed.length, 0);
  const snap = reporter.snapshot();
  assert.equal(snap.counters.proposed, 1, "a surfaced-but-not-applied finding bumps proposed");
  assert.ok(!snap.counters.reverted, "it was rejected BEFORE apply, so nothing reverted");
});

test("runAuditFix reporter: a unanimous §6 patch review drives the council gate to pass", async () => {
  const git = sensitiveGit();
  const { reporter } = reporterWithSink();
  const out = await runAuditFix(tmp(), [race()], {}, { sensitiveAutoApply: true, reporter }, baseDeps(git, {
    applyFix: async () => git.setChanged(["a.mjs"]),
    reviewPatch: async () => [{ seat: "claude", verdict: "confirm" }, { seat: "codex", verdict: "confirm" }, { seat: "grok", verdict: "confirm" }]
  }));
  assert.equal(out.fixed.length, 1);
  const snap = reporter.snapshot();
  assert.equal(snap.gate.name, "§6-council");
  assert.equal(snap.gate.state, "pass", "unanimous council review → gate pass");
  assert.equal(snap.counters.fixed, 1);
});

test("runAuditFix reporter: a dissenting §6 review vetoes the gate and reverts", async () => {
  const git = sensitiveGit();
  const { reporter } = reporterWithSink();
  const out = await runAuditFix(tmp(), [race()], {}, { sensitiveAutoApply: true, reporter }, baseDeps(git, {
    applyFix: async () => git.setChanged(["a.mjs"]),
    reviewPatch: async () => [{ seat: "claude", verdict: "confirm" }, { seat: "codex", verdict: "confirm" }, { seat: "grok", verdict: "dissent" }]
  }));
  assert.equal(out.fixed.length, 0);
  const snap = reporter.snapshot();
  assert.equal(snap.gate.state, "veto", "a dissent fails the §6 gate closed");
  assert.equal(snap.counters.reverted, 1, "and the reverted counter moves");
});

test("runAuditFix reporter: a green oracle baseline records the oracle gate as pass", async () => {
  const git = fakeGit();
  const { reporter } = reporterWithSink();
  const out = await runAuditFix(tmp(), [loc({ file: "a.mjs", title: "fix" })], {}, { reporter }, baseDeps(git, {
    applyFix: async () => git.setChanged(["a.mjs"]),
    runOracle: async () => ({ ok: true }),
    oracleName: "lint"
  }));
  assert.equal(out.fixed.length, 1);
  const snap = reporter.snapshot();
  // The oracle gate is recorded at baseline; a plain (non-sensitive) fix never overwrites it with §6.
  assert.equal(snap.gate.name, "oracle");
  assert.equal(snap.gate.state, "pass");
});

test("finding 5: a §6 review ERROR drives the gate to a terminal veto (never left stuck on 'running')", async () => {
  const git = sensitiveGit();
  const { reporter } = reporterWithSink();
  const out = await runAuditFix(tmp(), [race()], {}, { sensitiveAutoApply: true, reporter }, baseDeps(git, {
    applyFix: async () => git.setChanged(["a.mjs"]),
    reviewPatch: async () => {
      throw new Error("reviewer network error");
    }
  }));
  assert.equal(out.fixed.length, 0, "the patch is reverted to propose-only");
  const snap = reporter.snapshot();
  assert.equal(snap.gate.name, "§6-council");
  assert.equal(snap.gate.state, "veto", "the review-error exit emits a terminal veto, not a stuck 'running'");
  assert.equal(snap.counters.reverted, 1, "and the reverted counter moves");
});

test("finding 5: a §6 with no reviewable diff drives the gate to a terminal veto too", async () => {
  const git = fakeGit(); // no diffText → the §6 block cannot produce a diff to review
  const { reporter } = reporterWithSink();
  // reviewPatch must be present for the §6 path to be enabled at all (sensitiveAutoApply gate); it is
  // never called here because the no-diff guard trips first.
  const out = await runAuditFix(tmp(), [race()], {}, { sensitiveAutoApply: true, reporter }, baseDeps(git, {
    applyFix: async () => git.setChanged(["a.mjs"]),
    reviewPatch: async () => [{ seat: "claude", verdict: "confirm" }, { seat: "codex", verdict: "confirm" }, { seat: "grok", verdict: "confirm" }]
  }));
  assert.equal(out.fixed.length, 0);
  const snap = reporter.snapshot();
  assert.equal(snap.gate.name, "§6-council");
  assert.equal(snap.gate.state, "veto", "the no-diff exit is terminal, not stuck 'running'");
});

test("finding 4: a structural finding promoted to a successful apply is de-counted from proposed (not both proposed AND fixed)", async () => {
  const git = fakeGit();
  const { reporter } = reporterWithSink();
  // A cross-cutting structural finding → classifyFixable makes it propose-only (counted as `proposed`),
  // then the M9 structure pass applies it under the full gate ladder.
  const structural = { file: "a.mjs", title: "consolidate the duplicated config SSOT", lens: "architecture_ssot", category: "architecture_ssot", severity: "P1", scope: "cross-cutting" };
  const out = await runAuditFix(tmp(), [structural], {}, { structureAutoApply: true, reporter }, baseDeps(git, {
    runStructureTransform: async () => ({ ok: true, commit: "struct1234abcd" })
  }));
  assert.equal(out.fixed.length, 1, "the structural transform applied");
  const snap = reporter.snapshot();
  assert.equal(snap.counters.fixed, 1, "counted as fixed");
  assert.equal(snap.counters.committed, 1, "and committed");
  // Pre-counted as proposed (pre-loop rejected batch), then de-counted on the successful apply so it is
  // not reported as BOTH a standing proposal AND a fix.
  assert.equal(snap.counters.proposed ?? 0, 0, "the earlier 'proposed' count is undone on success");
});

test("runAuditFix without a reporter is unchanged (NOOP fallback, no throw)", async () => {
  const git = fakeGit();
  const out = await runAuditFix(tmp(), [loc({ file: "a.mjs", title: "fix me" })], {}, {}, baseDeps(git, { applyFix: async () => git.setChanged(["a.mjs"]) }));
  assert.equal(out.fixed.length, 1, "omitting options.reporter falls back to NOOP_REPORTER and changes nothing");
});

// LIVENESS in the fix phase (extends the 3f951f8 wait-heartbeat). The only stamp used to be
// `fix: N targets`, where a target is a FILE -- but the loop runs per FINDING, and each finding costs an
// agent write (up to 300s) + typecheck + the FULL suite. A live 2-target pass therefore sat 100+ MINUTES
// with progress.json frozen, and NOTHING could tell working from looping from hung: not the timestamp,
// not CPU (an LLM call is network-blocked at ~0%), not the phase. These pin that a run can always say
// which finding it is on and which step it is in.
test("fix phase heartbeat: every finding + expensive step stamps a phase (the 100-min blackbox)", async () => {
  const git = fakeGit();
  const { reporter } = reporterWithSink();
  const phases = [];
  const spy = { ...reporter, phase: (p, d) => (phases.push(`${p}|${d}`), reporter.phase(p, d)) };
  // TWO findings in the SAME file -> one "target", two per-finding iterations.
  const findings = [loc({ file: "a.mjs", title: "first" }), loc({ file: "a.mjs", title: "second" })];
  const out = await runAuditFix(
    tmp(),
    findings,
    {},
    { reporter: spy, oracleGate: false },
    baseDeps(git, { applyFix: async () => git.setChanged(["a.mjs"]) })
  );
  assert.equal(out.fixed.length, 2, "both findings still commit — the heartbeat is additive");

  assert.ok(phases.includes("fix|1 targets"), "the original target announcement is preserved");
  // The counter must run over FINDINGS (2), not targets (1) — that mismatch is what hid the cost.
  assert.ok(phases.some((p) => p.startsWith("fix|1/2 ")), "finding 1 of 2 announced");
  assert.ok(phases.some((p) => p.startsWith("fix|2/2 ")), "finding 2 of 2 announced");
  // The expensive steps must be nameable, or a stall is again indistinguishable from work.
  assert.ok(phases.some((p) => /^fix\|\d+\/2 authoring — a\.mjs$/.test(p)), "the agent write is announced");
  assert.ok(phases.some((p) => /^fix\|\d+\/2 full test suite — a\.mjs$/.test(p)), "the suite run is announced");
});

test("fix phase heartbeat: a reporter that throws never breaks a fix (telemetry is best-effort)", async () => {
  const git = fakeGit();
  const { reporter } = reporterWithSink();
  const hostile = { ...reporter, phase: () => { throw new Error("reporter exploded"); } };
  const out = await runAuditFix(
    tmp(),
    [loc({ file: "a.mjs", title: "fix me" })],
    {},
    { reporter: hostile, oracleGate: false },
    baseDeps(git, { applyFix: async () => git.setChanged(["a.mjs"]) })
  );
  assert.equal(out.fixed.length, 1, "the fix committed despite a throwing reporter");
});
