import assert from "node:assert/strict";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import test from "node:test";

import {
  buildFixWriteArgs,
  classifyFixable,
  contentProtectionReason,
  detectOracleCmd,
  enforceTouched,
  ineligibleReason,
  parsePorcelainZ,
  runAuditFix,
  scheduleFixes,
  toPosix
} from "../plugins/council/scripts/lib/audit-fix.mjs";

const tmp = () => fs.mkdtempSync(path.join(os.tmpdir(), "council-fix-"));

// --- eligibility (fail-closed) ----------------------------------------------

test("ineligibleReason is fail-closed: needs explicit localized scope + safe file + severity", () => {
  assert.equal(ineligibleReason({ severity: "P1", scope: "localized", file: "a.mjs" }), null);
  assert.match(ineligibleReason({ severity: "P1", scope: "cross-cutting", file: "a.mjs" }), /cross-cutting/);
  assert.match(ineligibleReason({ severity: "P1", file: "a.mjs" }), /fail-closed/, "missing scope is rejected, not fixed");
  assert.match(ineligibleReason({ severity: "P1", scope: "localish", file: "a.mjs" }), /fail-closed/);
  assert.match(ineligibleReason({ severity: "P1", scope: "localized" }), /no target file/);
  assert.match(ineligibleReason({ severity: "P1", scope: "localized", file: "../etc/passwd" }), /unsafe file path/);
  assert.match(ineligibleReason({ severity: "P1", scope: "localized", file: "C:\\Windows\\x" }), /unsafe file path/);
  assert.match(ineligibleReason({ severity: "nit", scope: "localized", file: "a.mjs" }), /severity gate/);
});

test("ineligibleReason rejects §6 sensitive classes (auth/crypto/concurrency/data) even when localized", () => {
  assert.match(ineligibleReason({ severity: "P1", scope: "localized", file: "a.mjs", category: "security" }), /sensitive/);
  assert.match(ineligibleReason({ severity: "P0", scope: "localized", file: "a.mjs", category: "concurrency" }), /sensitive/);
  assert.match(ineligibleReason({ severity: "P1", scope: "localized", file: "a.mjs", category: "auth" }), /sensitive/);
  assert.match(ineligibleReason({ severity: "P1", scope: "localized", file: "a.mjs", lens: "data_integrity" }), /sensitive/);
  assert.equal(ineligibleReason({ severity: "P1", scope: "localized", file: "a.mjs", category: "correctness" }), null, "ordinary bugs stay fixable");
});

test("ineligibleReason lets §6 through ONLY under consented sensitiveAutoApply; other gates still hold", () => {
  const race = { severity: "P1", scope: "localized", file: "a.mjs", category: "concurrency" };
  assert.match(ineligibleReason(race), /sensitive/, "default: propose-only");
  assert.equal(ineligibleReason(race, { sensitiveAutoApply: true }), null, "consented: flows to the council gate");
  // consent must NOT relax any other gate
  assert.match(ineligibleReason({ ...race, scope: "cross-cutting" }, { sensitiveAutoApply: true }), /cross-cutting/);
  assert.match(ineligibleReason({ ...race, file: "../x" }, { sensitiveAutoApply: true }), /unsafe file path/);
  assert.match(ineligibleReason({ ...race, severity: "nit" }, { sensitiveAutoApply: true }), /severity gate/);
});

test("PROTECTED_RE blocks secrets/CI/infra AND matches Windows separators", () => {
  for (const file of ["node_modules/x/i.mjs", ".git/config", "dist/b.js", ".env", ".env.production", ".github/workflows/ci.yml", "Dockerfile", "secrets/key.pem", "config/id.key"]) {
    assert.match(ineligibleReason({ severity: "P1", scope: "localized", file }), /protected/, `posix ${file} protected`);
  }
  // Windows-separator variants must ALSO be caught (normalized before matching).
  assert.match(ineligibleReason({ severity: "P1", scope: "localized", file: "node_modules\\pkg\\i.mjs" }), /protected/);
  assert.match(ineligibleReason({ severity: "P1", scope: "localized", file: ".github\\workflows\\ci.yml" }), /protected/);
});

test("contentProtectionReason catches migration/CI/generated/secret shapes, passes normal code", () => {
  assert.equal(contentProtectionReason("export const x = 1;\nfunction f(){ return 2; }\n"), null);
  assert.match(contentProtectionReason("// @generated by tool\nexport const x = 1;\n"), /generated/);
  assert.match(contentProtectionReason("exports.up = async (knex) => knex.schema.createTable('u', () => {});\n"), /migration/);
  assert.match(contentProtectionReason("await db.query('CREATE TABLE users (id int)');\n"), /migration/);
  assert.match(contentProtectionReason("pipeline {\n  stage('build') { sh 'make' }\n}\n"), /CI\/pipeline/);
  assert.match(contentProtectionReason("-----BEGIN RSA PRIVATE KEY-----\nMIIE...\n"), /secret/);
  // a param literally named apiKey in normal code must NOT trip the secret rule
  assert.equal(contentProtectionReason("function auth(apiKey) { return fetch(url, { apiKey }); }\n"), null);
});

test("generated marker protects only a file whose HEADER carries it (not a mid-file mention)", () => {
  assert.match(contentProtectionReason("// @generated by tool\nexport const x = 1;\n"), /generated/, "header marker -> protected");
  const midFile = `${"const x = 1;\n".repeat(120)}// prompt string: Do not edit files.\n`;
  assert.equal(contentProtectionReason(midFile), null, "'Do not edit' deep in a file (a prompt string) does not make it generated");
});

test("classifyFixable splits eligible vs rejected with reasons", () => {
  const { eligible, rejected } = classifyFixable([
    { severity: "P1", scope: "localized", file: "a.mjs", title: "ok" },
    { severity: "P2", scope: "cross-cutting", file: "b.mjs", title: "ssot" },
    { severity: "P0", scope: "localized", file: "dist/bundle.js", title: "built" },
    { severity: "P1", file: "c.mjs", title: "no-scope" }
  ]);
  assert.deepEqual(eligible.map((f) => f.file), ["a.mjs"]);
  assert.equal(rejected.length, 3);
});

// --- scheduling + guard + parsing -------------------------------------------

test("scheduleFixes groups by posix file (one writer/file), worst-first, serialized within", () => {
  const tasks = scheduleFixes([
    { severity: "P2", file: "a.mjs", title: "a-p2" },
    { severity: "P1", file: "b.mjs", title: "b-p1" },
    { severity: "P0", file: "a.mjs", title: "a-p0" }
  ]);
  assert.equal(tasks.length, 2);
  assert.equal(tasks[0].file, "a.mjs");
  assert.deepEqual(tasks[0].findings.map((f) => f.severity), ["P0", "P2"]);
});

test("scheduleFixes treats backslash and forward-slash paths as ONE file", () => {
  const tasks = scheduleFixes([
    { severity: "P1", file: "src\\a.mjs", title: "win" },
    { severity: "P2", file: "src/a.mjs", title: "posix" }
  ]);
  assert.equal(tasks.length, 1, "same physical file must not split into two tasks");
});

test("enforceTouched normalizes separators before comparing", () => {
  assert.deepEqual(enforceTouched(["a.mjs"], "a.mjs"), { ok: true, violations: [] });
  assert.deepEqual(enforceTouched(["src/a.mjs"], "src\\a.mjs"), { ok: true, violations: [] });
  assert.equal(enforceTouched(["a.mjs", "b.mjs"], "a.mjs").ok, false);
});

test("parsePorcelainZ handles plain edits and rename/copy pairs", () => {
  assert.deepEqual(parsePorcelainZ(" M a.mjs\0"), ["a.mjs"]);
  // a rename emits `R  new\0old\0`; BOTH paths must surface so a rename off the
  // target is caught as a violation (fail-closed).
  assert.deepEqual(parsePorcelainZ("R  new.mjs\0old.mjs\0"), ["old.mjs", "new.mjs"]);
  assert.deepEqual(parsePorcelainZ("?? x.mjs\0 M y.mjs\0"), ["x.mjs", "y.mjs"]);
});

test("toPosix strips backslashes and ./ prefix", () => {
  assert.equal(toPosix("a\\b\\c.mjs"), "a/b/c.mjs");
  assert.equal(toPosix("./a.mjs"), "a.mjs");
});

test("buildFixWriteArgs enables edit tools but denies exec/network, non-interactively", () => {
  const args = buildFixWriteArgs({ claudeModel: "claude-opus-4-8" });
  assert.ok(args.includes("Edit") && args.includes("Write"));
  assert.ok(args.indexOf("Bash") > args.indexOf("--disallowed-tools"), "Bash only in the deny list");
  assert.ok(args.includes("--strict-mcp-config"));
  assert.equal(args[args.indexOf("--permission-mode") + 1], "acceptEdits");
  assert.equal(args[args.indexOf("--model") + 1], "claude-opus-4-8");
});

// --- full orchestration with injected adapters -------------------------------

function fakeGit({ clean = true, repo = true } = {}) {
  const calls = [];
  let head = "base0000ffffffff";
  let changed = [];
  return {
    calls,
    setChanged(c) {
      changed = c;
    },
    isRepo: () => repo,
    isClean: () => clean,
    head: () => head,
    currentBranch: () => "master",
    createAndCheckout: (b, ref) => calls.push(["createAndCheckout", b, ref]),
    checkout: (r) => (calls.push(["checkout", r]), true),
    changedFiles: () => changed,
    resetHard: (ref) => {
      calls.push(["resetHard", ref]);
      changed = [];
    },
    commitFile: (file, msg) => {
      calls.push(["commitFile", file, msg]);
      head = `commit${calls.length}`;
      changed = [];
      return head;
    }
  };
}

const baseDeps = (git, over = {}) => ({
  git,
  fileExists: () => true,
  readFile: () => "export const x = 1;\n",
  testCmd: { cmd: "true", args: [] },
  runTests: async () => ({ ok: true }),
  resolveLedger: () => true,
  ...over
});

const loc = (o) => ({ severity: "P1", scope: "localized", ...o });

test("runAuditFix commits a fix when the edit is in-scope and tests pass", async () => {
  const git = fakeGit();
  const out = await runAuditFix(tmp(), [loc({ file: "a.mjs", title: "fix me" })], {}, {}, baseDeps(git, { applyFix: async () => git.setChanged(["a.mjs"]) }));
  assert.equal(out.ok, true);
  assert.equal(out.fixed.length, 1);
  assert.equal(out.fixed[0].verified, true);
  assert.ok(git.calls.some((c) => c[0] === "commitFile" && c[1] === "a.mjs"), "staged only the target file");
  assert.match(out.branch, /^council\/audit-fix-base0000/);
});

// --- §6 council gate: sensitive-class auto-apply -----------------------------

const sensitiveGit = (o) => Object.assign(fakeGit(o), { diffText: () => "@@ -1 +1 @@\n-old\n+new\n" });
const race = (o) => loc({ file: "a.mjs", title: "fix the race", category: "concurrency", ...o });

test("runAuditFix: a §6 fix commits only after a UNANIMOUS council patch-review", async () => {
  const git = sensitiveGit();
  const seen = [];
  const out = await runAuditFix(tmp(), [race()], {}, { sensitiveAutoApply: true }, baseDeps(git, {
    applyFix: async () => git.setChanged(["a.mjs"]),
    reviewPatch: async ({ diff }) => {
      seen.push(diff);
      return [{ seat: "claude", verdict: "confirm" }, { seat: "codex", verdict: "confirm" }, { seat: "grok", verdict: "confirm" }];
    }
  }));
  assert.equal(out.fixed.length, 1);
  assert.ok(out.fixed[0].council?.approved, "carries the council verdict");
  assert.match(seen[0], /\+new/, "the reviewer received the real unified diff");
  assert.ok(git.calls.some((c) => c[0] === "commitFile"));
});

test("runAuditFix: a §6 fix is reverted + proposed when any seat dissents (fail-closed veto)", async () => {
  const git = sensitiveGit();
  const out = await runAuditFix(tmp(), [race()], {}, { sensitiveAutoApply: true }, baseDeps(git, {
    applyFix: async () => git.setChanged(["a.mjs"]),
    reviewPatch: async () => [{ seat: "claude", verdict: "confirm" }, { seat: "codex", verdict: "confirm" }, { seat: "grok", verdict: "dissent" }]
  }));
  assert.equal(out.fixed.length, 0, "not committed");
  assert.ok(git.calls.some((c) => c[0] === "resetHard"), "reverted");
  assert.ok(out.rejected.some((r) => /council not unanimous/.test(r.reason)));
});

test("runAuditFix: a §6 fix is reverted when the reviewer throws (fail-closed)", async () => {
  const git = sensitiveGit();
  const out = await runAuditFix(tmp(), [race()], {}, { sensitiveAutoApply: true }, baseDeps(git, {
    applyFix: async () => git.setChanged(["a.mjs"]),
    reviewPatch: async () => { throw new Error("codex offline"); }
  }));
  assert.equal(out.fixed.length, 0);
  assert.ok(out.rejected.some((r) => /council review error/.test(r.reason)));
});

test("runAuditFix: §6 stays propose-only when consent is set but NO reviewer is injected", async () => {
  const git = sensitiveGit();
  let applied = 0;
  const out = await runAuditFix(tmp(), [race()], {}, { sensitiveAutoApply: true }, baseDeps(git, {
    applyFix: async () => { applied += 1; git.setChanged(["a.mjs"]); }
    // no reviewPatch injected
  }));
  assert.equal(out.fixed.length, 0);
  assert.equal(applied, 0, "writer never invoked — rejected upfront, no patch leaked");
  assert.ok(out.rejected.some((r) => /sensitive class/.test(r.reason)));
});

test("runAuditFix: §6 stays propose-only when consent is absent (default safety)", async () => {
  const git = sensitiveGit();
  let reviewed = 0;
  const out = await runAuditFix(tmp(), [race()], {}, {}, baseDeps(git, {
    applyFix: async () => git.setChanged(["a.mjs"]),
    reviewPatch: async () => { reviewed += 1; return []; }
  }));
  assert.equal(out.fixed.length, 0);
  assert.equal(reviewed, 0, "reviewer never consulted without consent");
  assert.ok(out.rejected.some((r) => /sensitive class/.test(r.reason)));
});

test("runAuditFix: §6 fails closed when no diff can be produced for review", async () => {
  const git = fakeGit(); // plain fakeGit has NO diffText
  let reviewed = 0;
  const out = await runAuditFix(tmp(), [race()], {}, { sensitiveAutoApply: true }, baseDeps(git, {
    applyFix: async () => git.setChanged(["a.mjs"]),
    reviewPatch: async () => { reviewed += 1; return []; }
  }));
  assert.equal(out.fixed.length, 0);
  assert.equal(reviewed, 0, "reviewer never consulted without a real diff");
  assert.ok(out.rejected.some((r) => /cannot produce a diff/.test(r.reason)));
});

test("runAuditFix ABORTS (ok:false, stranded) when a revert cannot restore the tree", async () => {
  const git = fakeGit();
  git.resetHard = () => { throw new Error("git reset --hard failed: disk full"); };
  const out = await runAuditFix(
    tmp(),
    [loc({ file: "a.mjs", title: "fix" }), loc({ file: "b.mjs", title: "second" })],
    {},
    {},
    baseDeps(git, { applyFix: async () => git.setChanged(["a.mjs", "sneaky.mjs"]) }) // out-of-scope → revert path
  );
  assert.equal(out.ok, false);
  assert.equal(out.stranded, true);
  assert.match(String(out.aborted), /tree not restored/);
  assert.ok(!git.calls.some((c) => c[0] === "commitFile"), "never commits over an unrestored tree");
});

test("runAuditFix resolves each committed fix in the ledger, but not on a red integration run", async () => {
  // happy: fix committed + integration green -> ledger resolved
  const git = fakeGit();
  const resolved = [];
  const out = await runAuditFix(tmp(), [loc({ file: "a.mjs", title: "fix me" })], {}, {}, baseDeps(git, {
    applyFix: async () => git.setChanged(["a.mjs"]),
    resolveLedger: (fp, status) => (resolved.push([fp, status]), true)
  }));
  assert.equal(out.ledgerResolved, 1);
  assert.equal(resolved.length, 1);
  assert.equal(resolved[0][1], "fixed-pending-merge", "provisional until the branch merges");

  // red final integration: commits kept on the branch but NOT marked fixed (may be discarded)
  const git2 = fakeGit();
  let n = 0;
  const resolved2 = [];
  const out2 = await runAuditFix(tmp(), [loc({ file: "a.mjs", title: "fix me" })], {}, {}, baseDeps(git2, {
    applyFix: async () => git2.setChanged(["a.mjs"]),
    runTests: async () => ({ ok: ++n === 1 }), // per-fix green, integration red
    resolveLedger: (fp, status) => (resolved2.push([fp, status]), true)
  }));
  assert.equal(out2.integrationFailed, true);
  assert.equal(out2.ledgerResolved, 0, "nothing resolved when the branch may be discarded");
  assert.equal(resolved2.length, 0);
});

test("runAuditFix does NOT resolve the ledger for unverified (--allow-untested) fixes", async () => {
  const git = fakeGit();
  const resolved = [];
  const out = await runAuditFix(tmp(), [loc({ file: "a.mjs", title: "fix" })], {}, { allowUntested: true }, baseDeps(git, {
    applyFix: async () => git.setChanged(["a.mjs"]),
    resolveLedger: (fp, s) => (resolved.push([fp, s]), true)
  }));
  assert.equal(out.fixed.length, 1);
  assert.equal(out.fixed[0].verified, false);
  assert.equal(out.ledgerResolved, 0, "an unverified fix must not suppress re-detection");
  assert.equal(resolved.length, 0);
});

test("runAuditFix reverts + rejects an out-of-scope edit; never commits", async () => {
  const git = fakeGit();
  const out = await runAuditFix(tmp(), [loc({ file: "a.mjs", title: "fix" })], {}, {}, baseDeps(git, { applyFix: async () => git.setChanged(["a.mjs", "sneaky.mjs"]) }));
  assert.equal(out.fixed.length, 0);
  assert.match(out.rejected[0].reason, /outside target/);
  assert.ok(git.calls.some((c) => c[0] === "resetHard"));
  assert.ok(!git.calls.some((c) => c[0] === "commitFile"));
});

test("runAuditFix skips a content-protected file WITHOUT ever invoking the writer", async () => {
  const git = fakeGit();
  let applied = 0;
  const out = await runAuditFix(tmp(), [loc({ file: "0001_init.mjs", title: "fix migration" })], {}, {}, baseDeps(git, {
    readFile: () => "exports.up = (knex) => knex.schema.createTable('u', () => {});\n",
    applyFix: async () => { applied += 1; git.setChanged(["0001_init.mjs"]); }
  }));
  assert.equal(applied, 0, "protected content must never reach the write runner");
  assert.equal(out.fixed.length, 0);
  assert.ok(out.rejected.some((r) => /protected by content/.test(r.reason)));
});

test("runAuditFix reverts a fix that changes the file's export surface", async () => {
  const git = fakeGit();
  let phase = 0;
  const out = await runAuditFix(tmp(), [loc({ file: "a.mjs", title: "drops an export" })], {}, {}, baseDeps(git, {
    // before: {x,y}; after the edit: {x} — y silently removed, tests would stay green
    readFile: () => (phase++ === 0 ? "export const x=1;\nexport const y=2;\n" : "export const x=1;\n"),
    applyFix: async () => git.setChanged(["a.mjs"])
  }));
  assert.equal(out.fixed.length, 0);
  assert.match(out.rejected[0].reason, /export surface changed.*removed y/);
  assert.ok(git.calls.some((c) => c[0] === "resetHard"), "reverted the surface-changing edit");
});

test("detectOracleCmd prefers typecheck, falls back to lint, else null", () => {
  const d = tmp();
  fs.writeFileSync(path.join(d, "package.json"), JSON.stringify({ scripts: { lint: "eslint .", typecheck: "tsc --noEmit" } }));
  assert.equal(detectOracleCmd(d).name, "typecheck");
  fs.writeFileSync(path.join(d, "package.json"), JSON.stringify({ scripts: { lint: "eslint ." } }));
  assert.equal(detectOracleCmd(d).name, "lint");
  fs.writeFileSync(path.join(d, "package.json"), JSON.stringify({ scripts: { build: "x" } }));
  assert.equal(detectOracleCmd(d), null);
});

test("runAuditFix reverts a fix that regresses the oracle (baseline was green)", async () => {
  const git = fakeGit();
  let oc = 0;
  const out = await runAuditFix(tmp(), [loc({ file: "a.mjs", title: "lint-breaker" })], {}, {}, baseDeps(git, {
    applyFix: async () => git.setChanged(["a.mjs"]),
    runOracle: async () => ({ ok: oc++ === 0 }) // baseline green, post-fix red
  }));
  assert.equal(out.fixed.length, 0);
  assert.match(out.rejected[0].reason, /oracle regression/);
  assert.ok(git.calls.some((c) => c[0] === "resetHard"));
});

test("runAuditFix disables the oracle gate when the baseline is already red", async () => {
  const git = fakeGit();
  let calls = 0;
  const out = await runAuditFix(tmp(), [loc({ file: "a.mjs", title: "fix" })], {}, {}, baseDeps(git, {
    applyFix: async () => git.setChanged(["a.mjs"]),
    runOracle: async () => (calls++, { ok: false }) // always red -> gate must disable, not block every fix
  }));
  assert.equal(out.oracleGated, false, "a red baseline disables the oracle gate");
  assert.equal(out.oracleState, "disabled");
  assert.equal(out.fixed.length, 1, "the fix still commits under the test gate");
  assert.equal(calls, 3, "baseline retried 3x before disabling, then not used per-fix");
});

test("runAuditFix protects test files, refuses to self-edit assertions", async () => {
  const git = fakeGit();
  const out = await runAuditFix(tmp(), [loc({ file: "tests/foo.test.mjs", title: "assertion inverted" })], {}, {}, baseDeps(git, { applyFix: async () => git.setChanged(["tests/foo.test.mjs"]) }));
  assert.equal(out.fixed?.length ?? 0, 0);
  assert.ok((out.rejected ?? []).some((r) => /protected/.test(r.reason)), "a test file is off-limits to the fix writer");
});

test("runAuditFix reverts a fix that INTRODUCES protected content (hardcoded secret)", async () => {
  const git = fakeGit();
  let phase = 0;
  const out = await runAuditFix(tmp(), [loc({ file: "a.mjs", title: "unblock" })], {}, {}, baseDeps(git, {
    readFile: () => (phase++ === 0 ? "export const x = 1;\n" : "export const x = 1;\nconst k = 'sk_live_ABCDEFGHIJKLMNOP';\n"),
    applyFix: async () => git.setChanged(["a.mjs"])
  }));
  assert.equal(out.fixed.length, 0);
  assert.match(out.rejected[0].reason, /introduced protected content/);
  assert.ok(git.calls.some((c) => c[0] === "resetHard"));
});

test("runAuditFix skips a file above the size cap (propose-only)", async () => {
  const git = fakeGit();
  const big = `export const x = 1;\n${"x".repeat(2_000_001)}`;
  let applied = 0;
  const out = await runAuditFix(tmp(), [loc({ file: "a.mjs", title: "huge" })], {}, {}, baseDeps(git, { readFile: () => big, applyFix: async () => { applied += 1; } }));
  assert.equal(applied, 0);
  assert.equal(out.fixed.length, 0);
  assert.ok(out.rejected.some((r) => /too large/.test(r.reason)));
});

test("runAuditFix does not revert on an oracle TIMEOUT (only on a real diagnostic)", async () => {
  const git = fakeGit();
  let oc = 0;
  const out = await runAuditFix(tmp(), [loc({ file: "a.mjs", title: "fix" })], {}, {}, baseDeps(git, {
    applyFix: async () => git.setChanged(["a.mjs"]),
    runOracle: async () => (oc++ === 0 ? { ok: true } : { ok: false, timedOut: true }) // baseline ok, post-fix times out
  }));
  assert.equal(out.fixed.length, 1, "a timeout skips the gate rather than reverting a possibly-correct fix");
});

test("coverage gate: a fix whose changed lines aren't executed is downgraded to propose-only", async () => {
  const git = fakeGit();
  git.diffLines = () => [5]; // the fix changed line 5
  const coverage = new Map([["a.mjs", new Set([1, 2])]]); // line 5 was never executed
  const out = await runAuditFix(tmp(), [loc({ file: "a.mjs", title: "fix" })], {}, { coverage }, baseDeps(git, { applyFix: async () => git.setChanged(["a.mjs"]) }));
  assert.equal(out.fixed.length, 0);
  assert.match(out.rejected.at(-1).reason, /not executed by any test/);
  assert.ok(git.calls.some((c) => c[0] === "resetHard"));
});

test("coverage gate: a fix whose changed lines ARE covered commits normally", async () => {
  const git = fakeGit();
  git.diffLines = () => [1];
  const coverage = new Map([["a.mjs", new Set([1, 2])]]);
  const out = await runAuditFix(tmp(), [loc({ file: "a.mjs", title: "fix" })], {}, { coverage }, baseDeps(git, { applyFix: async () => git.setChanged(["a.mjs"]) }));
  assert.equal(out.fixed.length, 1);
});

test("runAuditFix reverts + fails a fix when tests go red", async () => {
  const git = fakeGit();
  const out = await runAuditFix(tmp(), [loc({ file: "a.mjs", title: "fix" })], {}, {}, baseDeps(git, { applyFix: async () => git.setChanged(["a.mjs"]), runTests: async () => ({ ok: false, output: "1 failing" }) }));
  assert.equal(out.fixed.length, 0);
  assert.match(out.failed[0].reason, /tests failed/);
  assert.ok(git.calls.some((c) => c[0] === "resetHard"));
});

test("runAuditFix reverts + fails when the write runner throws", async () => {
  const git = fakeGit();
  const out = await runAuditFix(tmp(), [loc({ file: "a.mjs", title: "fix" })], {}, {}, baseDeps(git, { applyFix: async () => { throw new Error("runner exploded"); } }));
  assert.equal(out.fixed.length, 0);
  assert.match(out.failed[0].reason, /runner exploded/);
  assert.ok(git.calls.some((c) => c[0] === "resetHard"));
});

test("runAuditFix skips a finding the agent leaves unchanged", async () => {
  const git = fakeGit();
  const out = await runAuditFix(tmp(), [loc({ file: "a.mjs", title: "noop" })], {}, {}, baseDeps(git, { applyFix: async () => git.setChanged([]) }));
  assert.equal(out.skipped.length, 1);
  assert.equal(out.fixed.length, 0);
});

test("runAuditFix: a RED final integration run reports ok:false, base still returned", async () => {
  const git = fakeGit();
  let n = 0;
  const out = await runAuditFix(tmp(), [loc({ file: "a.mjs", title: "fix" })], {}, {}, baseDeps(git, {
    applyFix: async () => git.setChanged(["a.mjs"]),
    runTests: async () => ({ ok: ++n === 1 }) // per-fix gate green, final integration red
  }));
  assert.equal(out.fixed.length, 1, "the fix committed under its green per-fix gate");
  assert.equal(out.integrationFailed, true);
  assert.equal(out.ok, false, "a red integration run is NOT reported as success");
  assert.ok(git.calls.some((c) => c[0] === "checkout" && c[1] === "master"), "returned to base");
});

test("runAuditFix: same-file second-fix failure reverts to the FIRST fix's commit, keeping it", async () => {
  const git = fakeGit();
  let n = 0;
  const out = await runAuditFix(
    tmp(),
    [loc({ severity: "P1", file: "a.mjs", title: "first" }), loc({ severity: "P2", file: "a.mjs", title: "second" })],
    {},
    {},
    baseDeps(git, {
      applyFix: async () => git.setChanged(["a.mjs"]),
      // gate calls: 1=first(ok) 2=second(red) ; final integration=3(ok)
      runTests: async () => ({ ok: ++n !== 2 })
    })
  );
  assert.equal(out.fixed.length, 1, "first fix kept");
  assert.equal(out.fixed[0].finding.title, "first");
  assert.equal(out.failed.length, 1, "second fix failed");
  const commitSha = git.calls.find((c) => c[0] === "commitFile")[2] ? null : null; // (sha captured below)
  const firstCommit = out.fixed[0].commit;
  const resets = git.calls.filter((c) => c[0] === "resetHard").map((c) => c[1]);
  assert.ok(resets.includes(firstCommit), "second failure reset to the first fix's commit, not to base");
  void commitSha;
});

test("runAuditFix refuses without git, on a dirty tree, and without a test gate", async () => {
  const noRepo = await runAuditFix(tmp(), [], {}, {}, baseDeps(fakeGit({ repo: false })));
  assert.match(noRepo.error, /not a git repository/);
  const dirty = await runAuditFix(tmp(), [], {}, {}, baseDeps(fakeGit({ clean: false })));
  assert.match(dirty.error, /not clean/);
  const noGate = await runAuditFix(tmp(), [], {}, {}, { git: fakeGit(), fileExists: () => true, readFile: () => "", testCmd: null });
  assert.match(noGate.error, /test gate/);
});

test("runAuditFix --dry-run plans without a branch or writer, and honors the fail-closed gate", async () => {
  const git = fakeGit();
  let applied = 0;
  const out = await runAuditFix(
    tmp(),
    [loc({ file: "a.mjs", title: "fix" }), { severity: "P2", scope: "cross-cutting", file: "b.mjs", title: "ssot" }, { severity: "P1", file: "c.mjs", title: "no-scope" }],
    {},
    { dryRun: true },
    baseDeps(git, { applyFix: async () => { applied += 1; } })
  );
  assert.equal(out.dryRun, true);
  assert.equal(out.planned.length, 1, "only the localized+scoped finding is planned");
  assert.equal(out.rejected.length, 2, "cross-cutting AND missing-scope rejected");
  assert.equal(applied, 0);
  assert.equal(git.calls.length, 0);
});

test("runAuditFix caps the number of fixes via --max-fixes", async () => {
  const git = fakeGit();
  const findings = [loc({ file: "a.mjs", title: "1" }), loc({ file: "b.mjs", title: "2" }), loc({ file: "c.mjs", title: "3" })];
  const out = await runAuditFix(tmp(), findings, {}, { maxFixes: 2 }, baseDeps(git, { applyFix: async () => git.setChanged(["dummy"]) }));
  // 2 fixes attempted (each reverts as out-of-scope here), 1 capped away
  assert.equal(out.capped, 1);
});

test("runAuditFix continues an existing branch and can stay on it (fix loop)", async () => {
  const git = fakeGit();
  git.branchExists = (b) => b === "council/reuse"; // pretend the loop's branch already exists
  const out = await runAuditFix(tmp(), [loc({ file: "a.mjs", title: "fix" })], {}, { branch: "council/reuse", stayOnBranch: true }, baseDeps(git, { applyFix: async () => git.setChanged(["a.mjs"]) }));
  assert.equal(out.branch, "council/reuse");
  assert.ok(git.calls.some((c) => c[0] === "checkout" && c[1] === "council/reuse"), "checked out the existing branch");
  assert.ok(!git.calls.some((c) => c[0] === "createAndCheckout"), "did not create a new branch over the existing one");
  assert.equal(out.returnedToBase, false, "stayOnBranch keeps it on the fix branch for the next pass");
  assert.equal(out.spent, 1, "reports a spend proxy (fix attempts)");
  assert.deepEqual(out.changedFiles, ["a.mjs"]);
});

test("runAuditFix never auto-fixes cross-cutting findings even in a real run", async () => {
  const git = fakeGit();
  const out = await runAuditFix(tmp(), [{ severity: "P0", scope: "cross-cutting", file: "b.mjs", title: "consolidate" }], {}, {}, baseDeps(git, { applyFix: async () => git.setChanged(["b.mjs"]) }));
  assert.equal(out.fixed?.length ?? 0, 0);
  assert.ok(!out.branch);
  assert.ok(out.rejected.some((r) => /cross-cutting/.test(r.reason)));
});
