import fs from "node:fs";
import path from "node:path";

// Write audit findings to a living document as PROPOSALS. This is the safe half
// of the "fix" phase: cross-cutting / SSOT / architecture findings become
// documented migration proposals rather than auto-applied patches (the council's
// safety rule). It only writes the doc file - it never edits reviewed code.

const rankOf = (s) => ({ P0: 0, P1: 1, P2: 2, nit: 3 })[s] ?? 2;

/**
 * Render findings as a proposal document. `meta` may carry { source, coverage }.
 */
export function renderAuditDoc(findings, meta = {}) {
  const cross = findings.filter((f) => f.scope === "cross-cutting");
  const local = findings.filter((f) => f.scope !== "cross-cutting");
  const bySev = (list) => [...list].sort((a, b) => rankOf(a.severity) - rankOf(b.severity));
  const line = (f) =>
    `- **${f.severity}** [${f.category}] ${f.title}${f.file ? ` (\`${f.file}${f.line ? `:${f.line}` : ""}\`)` : ""}${f.confidence != null ? ` · conf ${f.confidence}` : ""}\n${f.detail ? `  - ${f.detail}\n` : ""}`;

  const L = [];
  L.push("# Audit — proposals");
  L.push("");
  L.push(`> Generated by \`/council:audit --doc\`${meta.source ? ` (${meta.source})` : ""}. These are **proposals** to verify, not applied changes. Cross-cutting items (SSOT / architecture) are documented migrations, deliberately NOT auto-patched.`);
  L.push("");
  L.push("## Cross-cutting / consolidation proposals");
  L.push("");
  if (cross.length) for (const f of bySev(cross)) L.push(line(f));
  else L.push("_None._\n");
  L.push("## Localized candidates (verify, then fix narrowly)");
  L.push("");
  if (local.length) for (const f of bySev(local)) L.push(line(f));
  else L.push("_None._\n");
  return L.join("\n");
}

/** Write the proposal doc; returns its absolute path. Only touches the doc file. */
export function writeAuditDoc(root, findings, meta = {}, { docPath } = {}) {
  const target = docPath ? path.resolve(root, docPath) : path.join(root, "docs", "AUDIT.md");
  fs.mkdirSync(path.dirname(target), { recursive: true });
  fs.writeFileSync(target, `${renderAuditDoc(findings, meta)}\n`, "utf8");
  return target;
}
